"""add password field

Revision ID: 32811b8243f8
Revises: f365f5847d43
Create Date: 2025-05-26 18:13:09.465383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32811b8243f8'
down_revision = 'f365f5847d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
